// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
//
//  NOTE:  There is a bug in ./bin/rails stimulus:manifest:update
//         Replace ./controller_name with controllers/controller_name

import { application } from "controllers/application"

import DismissController from "controllers/dismiss_controller"
application.register("dismiss", DismissController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import GalleryController from "controllers/gallery_controller"
application.register("gallery", GalleryController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import mobilenavController from "controllers/mobilenav_controller"
application.register("mobilenav", mobilenavController)
